apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-no-hostpath
  namespace: audit-zone
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: nginx:stable
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - name: app-logs
          mountPath: /app-logs
  volumes:
    - name: app-logs
      emptyDir: {}
