apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-non-root
  namespace: audit-zone
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:stable-alpine
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: nginx-tmp
          mountPath: /tmp
  volumes:
    - name: nginx-tmp
      emptyDir: {}
